services:
  - type: web
    name: legal-consult-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000  # Убедитесь, что запускаете FastAPI сервер
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8130728694:AAG9Sb_x5LL8oRv_egM8Aw3vldzT3swbNSI
      - key: OPENAI_API_KEY
        value: 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
      - key: WEBHOOK_URL
        value: https://telegram-gpt-bot-ok6q.onrender.com/telegram  # Убедитесь, что URL правильный
