services:
  - type: web
    name: legal-consult-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: WEBHOOK_URL
        value: "https://telegram-gpt-bot-ok6q.onrender.com/telegram"
      - key: GOOGLE_API_KEY
        value: ${GOOGLE_API_KEY}
      - key: GOOGLE_CSE_ID
        value: ${GOOGLE_CSE_ID}
      - key: PORT
        value: 10000
